//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XyuxiangObject.XyuxiangService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XyuxiangService.IXyuxiangService")]
    public interface IXyuxiangService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXyuxiangService/GetSum", ReplyAction="http://tempuri.org/IXyuxiangService/GetSumResponse")]
        int GetSum(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXyuxiangService/GetSum", ReplyAction="http://tempuri.org/IXyuxiangService/GetSumResponse")]
        System.Threading.Tasks.Task<int> GetSumAsync(int a, int b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IXyuxiangServiceChannel : XyuxiangObject.XyuxiangService.IXyuxiangService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XyuxiangServiceClient : System.ServiceModel.ClientBase<XyuxiangObject.XyuxiangService.IXyuxiangService>, XyuxiangObject.XyuxiangService.IXyuxiangService {
        
        public XyuxiangServiceClient() {
        }
        
        public XyuxiangServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XyuxiangServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XyuxiangServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XyuxiangServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetSum(int a, int b) {
            return base.Channel.GetSum(a, b);
        }
        
        public System.Threading.Tasks.Task<int> GetSumAsync(int a, int b) {
            return base.Channel.GetSumAsync(a, b);
        }
    }
}
